version: '3.9'
services:
  postgres-web-invitations:
    image: postgres:latest
    container_name: postgres-web-invitations
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - env/docker.env

  web-invitations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-invitations
    restart: unless-stopped
    env_file:
      - env/.env
    volumes:
      - ./logs/:/app/logs
      - ./media/:/app/media
      - ./static/:/app/static
    depends_on:
      - postgres-web-invitations
    command: gunicorn project.wsgi:application --bind 127.0.0.1:8000 --log-level debug
