# Generated by Django 5.0.1 on 2024-06-16 13:04

import guests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=128, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='DrinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=128, verbose_name='Напиток')),
            ],
            options={
                'verbose_name': 'напиток',
                'verbose_name_plural': 'напитки',
            },
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Имя события')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('time_event', models.TimeField(unique=True, verbose_name='Время начала события')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
        migrations.CreateModel(
            name='GuestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(help_text='данное поле не будет использовано в приветствии гостя(ей), оно будет использовано в качестве имени карточки и для создании индивидуальной ссылки', max_length=128, unique=True, verbose_name='Название карточки')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=256, null=True, unique=True, verbose_name='slug')),
                ('name_guest', models.CharField(help_text='Добавь именена/имя сразу с приветсвием, например: "Дорогие Ивановы", "Дорогие Екатерина и Владимир", "Дорогой Дмитрий", "Дорогая Светалана"', max_length=128, validators=[guests.validators.check_name], verbose_name='Имя(Фамилия) гостя(ей)')),
                ('visit', models.CharField(blank=True, choices=[('да', 'да'), ('нет', 'нет')], max_length=3, null=True, verbose_name='Придут?')),
                ('to_transfer', models.CharField(blank=True, choices=[('да', 'да'), ('нет', 'нет')], max_length=3, null=True, verbose_name='Нужен трансфер НА мероприятие?')),
                ('from_transfer', models.CharField(blank=True, choices=[('да', 'да'), ('нет', 'нет')], max_length=3, null=True, verbose_name='Нужен трансфер С мероприятия?')),
                ('date_time_answer', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время ответа')),
                ('date_time_answer_edit', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время редактирования ответа')),
                ('drinks', models.ManyToManyField(blank=True, related_name='drinks', to='guests.drinkmodel', verbose_name='Какие напитки будут?')),
                ('from_city', models.ManyToManyField(blank=True, null=True, to='guests.citymodel', verbose_name='С какого города забрать на мероприятие?')),
                ('to_city', models.ManyToManyField(blank=True, related_name='cites', to='guests.citymodel', verbose_name='В какой город отвезти после мероприятия?')),
            ],
            options={
                'verbose_name': 'гость',
                'verbose_name_plural': 'гости',
            },
        ),
    ]
