# Generated by Django 5.0.1 on 2024-06-15 09:48

import guests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=128, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='DrinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(max_length=128, verbose_name='Напиток')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('name', models.CharField(help_text='данное поле не будет использовано в приветствии гостя(ей), оно будет использовано в качестве имени карточки и для создании индивидуальной ссылки', max_length=128, unique=True, verbose_name='Название карточки')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=256, null=True, unique=True, verbose_name='slug')),
                ('name_first', models.CharField(help_text='Имя первого гостя. Будет отображаться в приветствии.Если будет более двух гостей, то нужно обощить их общей фамилией, если она общая, иначе нужно на каждого гостя сделать свою карточку', max_length=128, validators=[guests.validators.check_name], verbose_name='Имя(Фамилия) гостя(ей)')),
                ('sex', models.CharField(help_text='Если их будет более одно, то установить нужно "они"', max_length=3, verbose_name='Пол первого гостя')),
                ('visit_first_guest', models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=3, verbose_name='Придет?')),
                ('name_second', models.CharField(blank=True, help_text='В этом поле ожидается парень/девушка/супруг/супруга первого гостя', max_length=128, null=True, validators=[guests.validators.check_name])),
                ('visit_second_guest', models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=3, verbose_name='Придет?')),
                ('to_transfer', models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=3, verbose_name='Нужен трансфер НА мероприятие?')),
                ('from_transfer', models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=3, verbose_name='Нужен трансфер С мероприятия?')),
                ('date_time_answer', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время ответа')),
                ('date_time_answer_edit', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время редактирования ответа')),
                ('drinks', models.ManyToManyField(related_name='drinks', to='guests.drinkmodel', verbose_name='Какие напитки будут?')),
                ('from_city', models.ManyToManyField(to='guests.citymodel', verbose_name='С какого города забрать на мероприятие?')),
                ('to_city', models.ManyToManyField(related_name='cites', to='guests.citymodel', verbose_name='В какой город отвезти после мероприятия?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
