# Generated by Django 5.0.1 on 2024-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_remove_eventmodel_date_event_eventmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала события'),
        ),
    ]
