# Generated by Django 5.0.1 on 2024-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_eventmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='time_event',
            field=models.TimeField(verbose_name='Время начала события'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmodel',
            unique_together={('date', 'time_event')},
        ),
    ]
